spring:
  application.name: onlineEducation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: mySql
    password: 1234567890

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#        ddl-auto: update
        format_sql: true


